from enum import Enum

from pycalcmodel.core.variable import CreateModelVariableEnum, ModelVariableFormat
from pyradioconfig.parts.lion.calculators.calc_global import CalcGlobalLion


class CalcGlobalCurl(CalcGlobalLion):

    def buildVariables(self, model):
        super().buildVariables(model)
        self._addModelVariable(model, 'viterbi_enable', bool, ModelVariableFormat.DECIMAL, desc='Enable Viterbi demodulator')
        self._addModelVariable(model, 'lock_bwsel', float, ModelVariableFormat.DECIMAL, units='Hz', desc='reduced bwsel after oneshot AFC. ')
        self._addModelVariable(model, 'lock_bandwidth_hz', int, ModelVariableFormat.DECIMAL)
        self._addModelVariable(model, 'demod_bandwidth_hz', int, ModelVariableFormat.DECIMAL)

    def _add_common_regs(self, model):
        super()._add_common_regs(model)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00.SET0CSDCOEFF0', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00.SET0CSDCOEFF1', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00.SET0CSDCOEFF2', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00.SET0CSDCOEFF3', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01.SET0CSDCOEFF4', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01.SET0CSDCOEFF5', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01.SET0CSDCOEFF6', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE02.SET0CSDCOEFF7', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE02.SET0CSDCOEFF8', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE02.SET0CSDCOEFF9', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE03.SET0CSDCOEFF10', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE03.SET0CSDCOEFF11', int, ModelVariableFormat.HEX)

        self._addModelRegister(model, 'MODEM.CHFCSDCOE00S.SET0CSDCOEFF0S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00S.SET0CSDCOEFF1S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00S.SET0CSDCOEFF2S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00S.SET0CSDCOEFF3S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00S.SET0CSDCOEFF4S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00S.SET0CSDCOEFF5S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00S.SET0CSDCOEFF6S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01S.SET0CSDCOEFF7S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01S.SET0CSDCOEFF8S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01S.SET0CSDCOEFF9S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01S.SET0CSDCOEFF10S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01S.SET0CSDCOEFF11S', int, ModelVariableFormat.HEX)

        self._addModelRegister(model, 'MODEM.CHFCSDCOE10.SET1CSDCOEFF0', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10.SET1CSDCOEFF1', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10.SET1CSDCOEFF2', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10.SET1CSDCOEFF3', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE11.SET1CSDCOEFF4', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE11.SET1CSDCOEFF5', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE11.SET1CSDCOEFF6', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE12.SET1CSDCOEFF7', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE12.SET1CSDCOEFF8', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE12.SET1CSDCOEFF9', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE13.SET1CSDCOEFF10', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE13.SET1CSDCOEFF11', int, ModelVariableFormat.HEX)

        self._addModelRegister(model, 'MODEM.CHFCSDCOE10S.SET1CSDCOEFF0S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10S.SET1CSDCOEFF1S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10S.SET1CSDCOEFF2S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10S.SET1CSDCOEFF3S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10S.SET1CSDCOEFF4S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10S.SET1CSDCOEFF5S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE10S.SET1CSDCOEFF6S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE11S.SET1CSDCOEFF7S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE11S.SET1CSDCOEFF8S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE11S.SET1CSDCOEFF9S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE11S.SET1CSDCOEFF10S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE11S.SET1CSDCOEFF11S', int, ModelVariableFormat.HEX)

        self._addModelRegister(model, 'MODEM.CHFCSDCOE00NADM.NADMCSDCOEFF0', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00NADM.NADMCSDCOEFF1', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00NADM.NADMCSDCOEFF2', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00NADM.NADMCSDCOEFF3', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01NADM.NADMCSDCOEFF4', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01NADM.NADMCSDCOEFF5', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01NADM.NADMCSDCOEFF6', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE02NADM.NADMCSDCOEFF7', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE02NADM.NADMCSDCOEFF8', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE02NADM.NADMCSDCOEFF9', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE03NADM.NADMCSDCOEFF10', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE03NADM.NADMCSDCOEFF11', int, ModelVariableFormat.HEX)

        self._addModelRegister(model, 'MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF0S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF1S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF2S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF3S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF4S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF5S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF6S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF7S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF8S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF9S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF10S', int, ModelVariableFormat.HEX)
        self._addModelRegister(model, 'MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF11S', int, ModelVariableFormat.HEX)
