from pyradioconfig.parts.lion.calculators.calc_misc import CalcMiscLion


class CalcMiscCurl(CalcMiscLion):

    def calc_misc_Leopard(self, model):
        # Remove RAC_CLKMULTEN registers from default calculation
        self._reg_write(model.vars.FRC_DFLCTRL_DFLBOIOFFSET, 0)
        self._reg_write(model.vars.FRC_CTRL_WAITEOFEN, 0)
        self._reg_write(model.vars.FRC_TRAILTXDATACTRL_TRAILTXREPLEN, 0)
        self._reg_write(model.vars.FRC_TRAILTXDATACTRL_TXSUPPLENOVERIDE, 0)
        self._reg_write(model.vars.FRC_WCNTCMP3_SUPPLENFIELDLOC, 0)
        self._reg_write(model.vars.FRC_BOICTRL_BOIEN, 0)
        self._reg_write(model.vars.FRC_BOICTRL_BOIFIELDLOC, 0)
        self._reg_write(model.vars.FRC_BOICTRL_BOIBITPOS, 0)
        self._reg_write(model.vars.FRC_BOICTRL_BOIMATCHVAL, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_DSLMODE, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_DSLBITORDER, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_DSLSHIFT, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_DSLOFFSET, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_DSLBITS, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_DSLMINLENGTH, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_RXSUPRECEPMODE, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_STORESUP, 0)
        self._reg_write(model.vars.FRC_DSLCTRL_SUPSHFFACTOR, 0)
        self._reg_write(model.vars.FRC_WCNTCMP4_SUPPLENGTH, 0)
        self._reg_write(model.vars.MODEM_DIGMIXCTRL_DIGMIXFB, 0)
        self._reg_write(model.vars.MODEM_VTTRACK_SYNCTIMEOUTSEL, 1)
        self._reg_write(model.vars.MODEM_LRFRC_LRCORRMODE, 1)
        self._reg_write(model.vars.MODEM_ETSCTRL_ETSLOC, 0)
        self._reg_write(model.vars.MODEM_ETSCTRL_CAPTRIG, 0)
        self._reg_write(model.vars.MODEM_ANTSWCTRL_ANTDFLTSEL, 0)
        self._reg_write(model.vars.MODEM_ANTSWCTRL_ANTCOUNT, 0)
        self._reg_write(model.vars.MODEM_ANTSWCTRL_ANTSWTYPE, 0)
        self._reg_write(model.vars.MODEM_ANTSWCTRL_CFGANTPATTEN, 0)
        self._reg_write(model.vars.MODEM_ANTSWCTRL_ANTSWENABLE, 0)
        self._reg_write(model.vars.MODEM_ANTSWCTRL_EXTDSTOPPULSECNT, 30)
        self._reg_write(model.vars.MODEM_ANTSWSTART_ANTSWSTARTTIM, 0)
        self._reg_write(model.vars.MODEM_ANTSWEND_ANTSWENDTIM, 0)
        self._reg_write(model.vars.MODEM_CFGANTPATT_CFGANTPATTVAL, 0)
        self._reg_write(model.vars.MODEM_ETSTIM_ETSTIMVAL, 0)
        self._reg_write(model.vars.MODEM_ETSTIM_ETSCOUNTEREN, 0)
        self._reg_write(model.vars.MODEM_ANTSWCTRL1_TIMEPERIOD, 436906)
        self._reg_write(model.vars.MODEM_COCURRMODE_CONCURRENT, 0)
        self._reg_write(model.vars.MODEM_ANTDIVCTRL_ADPRETHRESH, 0)
        self._reg_write(model.vars.MODEM_ANTDIVCTRL_ENADPRETHRESH, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT2_DISMAXPEAKTRACKMODE, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT2_BBSSDIFFCHVAL, 0)

        self._reg_write(model.vars.RAC_LNAMIXDEBUG_LNAMIXDISMXR, 0)
        self._reg_write(model.vars.RAC_LNAMIXTRIM0_LNAMIXRFPKDBWSEL, 2)
        self._reg_write(model.vars.RAC_LNAMIXTRIM0_LNAMIXRFPKDCALDM, 16)
        self._reg_write(model.vars.RAC_LNAMIXTRIM0_LNAMIXTRIMVREG, 8)
        self._reg_write(model.vars.RAC_LNAMIXTRIM1_LNAMIXLNACAPSEL, 0)
        self._reg_write(model.vars.RAC_LNAMIXTRIM1_LNAMIXMXRBIAS, 2)
        self._reg_write(model.vars.RAC_LNAMIXTRIM1_LNAMIXNCASADJ, 2)
        self._reg_write(model.vars.RAC_LNAMIXTRIM1_LNAMIXPCASADJ, 2)
        self._reg_write(model.vars.RAC_LNAMIXTRIM1_LNAMIXVOUTADJ, 8)
        self._reg_write(model.vars.RAC_PGACTRL_PGABWMODE, 0)
        self._reg_write(model.vars.RAC_SYTRIM1_SYLODIVSGTESTDIV, 0)
        self._reg_write(model.vars.RAC_SYMMDCTRL_SYMMDMODE, 2)
        self._reg_write(model.vars.RAC_SYNTHCTRL_MMDPOWERBALANCEDISABLE, 1)
        self._reg_write(model.vars.RAC_SYNTHREGCTRL_MMDLDOVREFTRIM, 3)
        self._reg_write_default(model.vars.RAC_IFADCTRIM0_IFADCSIDETONEAMP)
        self._reg_write_default(model.vars.FRC_AUTOCG_AUTOCGEN)

        if model.vars.SYNTH_LPFCTRL1CAL_OP1BWCAL.value_forced is None:
            self._reg_do_not_care(model.vars.SYNTH_LPFCTRL1CAL_OP1BWCAL)
        if model.vars.SYNTH_LPFCTRL1CAL_OP1COMPCAL.value_forced is None:
            self._reg_do_not_care(model.vars.SYNTH_LPFCTRL1CAL_OP1COMPCAL)
        if model.vars.SYNTH_LPFCTRL1CAL_RZVALCAL.value_forced is None:
            self._reg_do_not_care(model.vars.SYNTH_LPFCTRL1CAL_RZVALCAL)
        if model.vars.SYNTH_LPFCTRL1CAL_RPVALCAL.value_forced is None:
            self._reg_do_not_care(model.vars.SYNTH_LPFCTRL1CAL_RPVALCAL)
        if model.vars.SYNTH_LPFCTRL1CAL_RFBVALCAL.value_forced is None:
            self._reg_do_not_care(model.vars.SYNTH_LPFCTRL1CAL_RFBVALCAL)

    def calc_misc_Panther(self, model):
        self._reg_write(model.vars.MODEM_CTRL0_OOKASYNCPIN, 0)
        self._reg_write(model.vars.MODEM_CTRL0_DETDIS, 0)
        self._reg_write(model.vars.MODEM_CTRL0_DEMODRAWDATASEL, 0)
        self._reg_write(model.vars.MODEM_CTRL1_TXSYNC, 0)
        self._reg_write(model.vars.MODEM_CTRL2_SQITHRESH, 0)
        self._reg_write(model.vars.MODEM_CTRL2_RXFRCDIS, 0)
        self._reg_write(model.vars.MODEM_CTRL2_TXPINMODE, 0)
        self._reg_write(model.vars.MODEM_CTRL2_DEVMULA, 0)
        self._reg_write(model.vars.MODEM_CTRL2_DEVMULB, 0)
        self._reg_write(model.vars.MODEM_CTRL2_RATESELMODE, 0)
        self._reg_write(model.vars.MODEM_CTRL2_DMASEL, 0)
        self._reg_write(model.vars.MODEM_CTRL3_PRSDINEN, 0)
        self._reg_write(model.vars.MODEM_CTRL3_RAMTESTEN, 0)
        self._reg_write(model.vars.MODEM_CTRL4_PHASECLICKFILT, 0)
        self._reg_write(model.vars.MODEM_CTRL4_OFFSETPHASESCALING, 0)
        self._reg_write(model.vars.MODEM_CTRL4_CLKUNDIVREQ, 0)
        self._reg_write(model.vars.MODEM_CTRL5_DEMODRAWDATASEL2, 0)

        self._reg_write(model.vars.MODEM_CTRL6_CODINGB, 0)
        self._reg_write(model.vars.MODEM_CTRL6_RXRESTARTUPONRSSI, 0)
        self._reg_write(model.vars.MODEM_CTRL6_RXRESTARTUPONSHORTRSSI, 0)

        self._reg_write(model.vars.MODEM_CF_ADCBITORDERI, 0)
        self._reg_write(model.vars.MODEM_CF_ADCBITORDERQ, 0)
        self._reg_write(model.vars.MODEM_PRE_PRESYMB4FSK, 0)
        self._reg_write(model.vars.MODEM_PRE_SYNCSYMB4FSK, 0)
        self._reg_write(model.vars.MODEM_TIMING_TIMSEQINVEN, 0)
        self._reg_write(model.vars.MODEM_DCCOMP_DCESTIEN, 1) # Explicitly enable DC Offset Estimation using tracking filter (non-default value) https://jira.silabs.com/browse/MCUW_RADIO_CFG-747
        self._reg_write(model.vars.MODEM_DCCOMP_DCCOMPEN, 1) # Explicitly enable DC Offset compensation using tracking filter (non-default value) https://jira.silabs.com/browse/MCUW_RADIO_CFG-747
        self._reg_write(model.vars.MODEM_DCCOMP_DCRSTEN, 0)
        self._reg_write(model.vars.MODEM_DCCOMP_DCCOMPFREEZE, 0)
        self._reg_write(model.vars.MODEM_DCCOMP_DCCOMPGEAR, 3)
        self._reg_write(model.vars.MODEM_DCCOMP_DCLIMIT, 0)
        self._reg_write(model.vars.MODEM_DCCOMPFILTINIT_DCCOMPINITVALI, 0)
        self._reg_write(model.vars.MODEM_DCCOMPFILTINIT_DCCOMPINITVALQ, 0)
        self._reg_write(model.vars.MODEM_DCCOMPFILTINIT_DCCOMPINIT, 0)

        self._reg_write(model.vars.MODEM_DSACTRL_TRANRSTDSA, 0)
        self._reg_write(model.vars.MODEM_AUTOCG_AUTOCGEN, 0)
        self._reg_write(model.vars.MODEM_DIRECTMODE_DMENABLE, 0)
        self._reg_write(model.vars.MODEM_DIRECTMODE_SYNCASYNC, 0)
        self._reg_write(model.vars.MODEM_DIRECTMODE_SYNCPREAM, 3)
        self._reg_write(model.vars.MODEM_DIRECTMODE_CLKWIDTH, 1)

        self._reg_write(model.vars.MODEM_LONGRANGE1_LOGICBASEDPUGATE, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE1_LOGICBASEDLRDEMODGATE, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE6_LRCHPWRTH11, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE6_LRCHPWRSH12, 0)

        self._reg_write(model.vars.MODEM_DSATHD3_SPIKETHDLO, 100)
        self._reg_write(model.vars.MODEM_DSATHD3_UNMODTHDLO, 4)
        self._reg_write(model.vars.MODEM_DSATHD3_FDEVMINTHDLO, 12)
        self._reg_write(model.vars.MODEM_DSATHD3_FDEVMAXTHDLO, 120)
        self._reg_write(model.vars.MODEM_DSATHD4_POWABSTHDLO, 5000)
        self._reg_write(model.vars.MODEM_DSATHD4_ARRTOLERTHD0LO, 2)
        self._reg_write(model.vars.MODEM_DSATHD4_ARRTOLERTHD1LO, 4)
        self._reg_write(model.vars.MODEM_DSATHD4_SWTHD, 0)

        self._reg_write(model.vars.MODEM_SYNCPROPERTIES_SYNCCORRCLR, 0)
        self._reg_write(model.vars.MODEM_SYNCPROPERTIES_SYNCSECPEAKTH, 0)
        self._reg_write(model.vars.MODEM_DIGIGAINCTRL_DIGIGAINEN, 0)
        self._reg_write(model.vars.MODEM_DIGIGAINCTRL_DIGIGAINSEL, 0)
        self._reg_write(model.vars.MODEM_DIGIGAINCTRL_DIGIGAINDOUBLE, 0)
        self._reg_write(model.vars.MODEM_DIGIGAINCTRL_DIGIGAINHALF, 0)
        self._reg_write(model.vars.MODEM_DIGIGAINCTRL_DEC0GAIN, 0)

        self._reg_write(model.vars.MODEM_PADEBUG_MANPACLKAMPCTRL, 0)
        self._reg_write(model.vars.MODEM_PADEBUG_ENMANPACLKAMPCTRL, 0)
        self._reg_write(model.vars.MODEM_PADEBUG_ENMANPAPOWER, 0)
        self._reg_write(model.vars.MODEM_PADEBUG_ENMANPASELSLICE, 0)

        self._reg_write(model.vars.FRC_CTRL_RATESELECT, 0)

        self._reg_write(model.vars.MODEM_MIXCTRL_ANAMIXMODE, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSA_BLEIQDSAEN, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSA_BLEIQDSATH, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSA_BLEIQDSAIIRCOEFPWR, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSA_BLEIQDSADIFFTH1, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT1_FREQSCALEIQDSA, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT1_CHPWRFIRAVGEN, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT1_CHPWRFIRAVGVAL, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT1_CORRIIRAVGMULFACT, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT1_BLEIQDSAADDRBIAS, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT1_BLEIQDSATHCOMB, 0)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT1_MAXCORRCNTIQDSA, 7)
        self._reg_write(model.vars.MODEM_BLEIQDSAEXT1_IIRRST, 0)

    def calc_misc(self, model):
        # Copied from nixi, remove unused registers

        self._reg_write(model.vars.MODEM_CTRL0_FRAMEDETDEL, 0)
        self._reg_write(model.vars.MODEM_CTRL1_SYNCERRORS, 0)
        self._reg_write(model.vars.MODEM_CTRL1_SYNC1INV, 0)
        self._reg_write(model.vars.MODEM_CTRL2_BRDIVB, 0)
        self._reg_write(model.vars.MODEM_CTRL2_BRDIVA, 0)
        self._reg_write(model.vars.MODEM_CTRL4_ADCSATDENS, 0)
        self._reg_write(model.vars.MODEM_CTRL4_ADCSATLEVEL, 6)
        self._reg_write(model.vars.MODEM_PRE_DSSSPRE, 0)
        self._reg_write(model.vars.MODEM_TIMING_TSAGCDEL, 0)
        self._reg_write(model.vars.MODEM_TIMING_TIMSEQSYNC, 0)
        self._reg_write(model.vars.MODEM_TIMING_FASTRESYNC, 0)
        self._reg_write(model.vars.MODEM_AFC_AFCTXMODE, 0)
        self._reg_write(model.vars.MODEM_DSATHD0_SPIKETHD, 0x64)
        self._reg_write(model.vars.MODEM_DSATHD0_UNMODTHD, 4)
        self._reg_write(model.vars.MODEM_DSATHD0_FDEVMINTHD, 12)
        self._reg_write(model.vars.MODEM_DSATHD0_FDEVMAXTHD, 0x78)
        self._reg_write(model.vars.MODEM_DSATHD1_POWABSTHD, 0x1388)
        self._reg_write(model.vars.MODEM_DSATHD1_POWRELTHD, 0)
        self._reg_write(model.vars.MODEM_DSATHD1_DSARSTCNT, 2)
        self._reg_write(model.vars.MODEM_DSATHD1_RSSIJMPTHD, 6)
        self._reg_write(model.vars.MODEM_DSATHD1_FREQLATDLY, 1)
        self._reg_write(model.vars.MODEM_DSATHD1_PWRFLTBYP, 1)
        self._reg_write(model.vars.MODEM_DSATHD1_AMPFLTBYP, 1)
        self._reg_write(model.vars.MODEM_DSATHD1_PWRDETDIS, 1)
        self._reg_write(model.vars.MODEM_DSATHD1_FREQSCALE, 0)
        self._reg_write(model.vars.MODEM_DSACTRL_ARRTOLERTHD0, 2)
        self._reg_write(model.vars.MODEM_DSACTRL_ARRTOLERTHD1, 4)
        self._reg_write(model.vars.MODEM_DSACTRL_SCHPRD, 0)
        self._reg_write(model.vars.MODEM_DSACTRL_FREQAVGSYM, 1)
        self._reg_write(model.vars.MODEM_DSACTRL_DSARSTON, 1)
        self._reg_write(model.vars.MODEM_DSACTRL_LOWDUTY, 0)

        self._reg_write(model.vars.MODEM_VTTRACK_TIMCHK, 0)
        self._reg_write(model.vars.MODEM_VTTRACK_TIMEOUTMODE, 1)

        self._reg_write(model.vars.MODEM_VTCORRCFG1_CORRSHFTLEN, 0x20)

        self._reg_write(model.vars.MODEM_VTCORRCFG1_BUFFHEAD, 2)

        self._reg_write(model.vars.MODEM_CTRL4_SOFTDSSSMODE, 0)
        self._reg_write(model.vars.MODEM_CTRL4_PREDISTRST, 0)
        self._reg_write(model.vars.MODEM_CTRL4_PREDISTAVG, 0)
        self._reg_write(model.vars.MODEM_CTRL4_PREDISTDEB, 0)
        self._reg_write(model.vars.MODEM_CTRL4_PREDISTGAIN, 0)
        self._reg_write(model.vars.MODEM_CTRL5_RESYNCLIMIT, 0)
        self._reg_write(model.vars.MODEM_CTRL6_RXBRCALCDIS, 0)
        self._reg_write(model.vars.MODEM_CTRL6_DEMODRESTARTALL, 0)
        self._reg_write(model.vars.MODEM_DSACTRL_AGCBAUDEN, 0)
        self._reg_write(model.vars.MODEM_DSACTRL_RESTORE, 0)
        self._reg_write(model.vars.MODEM_DSACTRL_AMPJUPTHD, 0)
        self._reg_write(model.vars.MODEM_DSACTRL_GAINREDUCDLY, 0)
        self._reg_write(model.vars.MODEM_CTRL0_DUALCORROPTDIS, 0)
        self._reg_write(model.vars.MODEM_CGCLKSTOP_FORCEOFF, 0)
        self._reg_write(model.vars.AGC_RSSISTEPTHR_DEMODRESTARTPER, 0)
        self._reg_write(model.vars.AGC_RSSISTEPTHR_DEMODRESTARTTHR, 0)
        self._reg_write(model.vars.AGC_RSSISTEPTHR_POSSTEPTHR, 0)
        self._reg_write(model.vars.AGC_RSSISTEPTHR_NEGSTEPTHR, 0)
        self._reg_write(model.vars.AGC_RSSISTEPTHR_STEPPER, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE_LRCORRTHD, 0x3E8)
        self._reg_write(model.vars.MODEM_LONGRANGE_LRTIMCORRTHD, 0x0FA)
        self._reg_write(model.vars.MODEM_LONGRANGE_LRCORRSCHWIN, 0xA)
        self._reg_write(model.vars.MODEM_LONGRANGE_LRBLE, 0)
        self._reg_write(model.vars.MODEM_LRFRC_CI500, 1)
        self._reg_write(model.vars.MODEM_LRFRC_FRCACKTIMETHD, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE_LRDEC, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE_LRBLEDSA, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE1_LRSS, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE1_LRTIMEOUTTHD, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE6_LRCHPWRSPIKETH, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE6_LRSPIKETHD, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE1_LRSPIKETHADD, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE1_CHPWRACCUDEL, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE1_HYSVAL, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE1_AVGWIN, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE2_LRCHPWRTH1, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE2_LRCHPWRTH2, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE2_LRCHPWRTH3, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE2_LRCHPWRTH4, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE3_LRCHPWRTH5, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE3_LRCHPWRTH6, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE3_LRCHPWRTH7, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE3_LRCHPWRTH8, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE4_LRCHPWRTH9, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE4_LRCHPWRTH10, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE4_LRCHPWRSH1, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE4_LRCHPWRSH2, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE4_LRCHPWRSH3, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE4_LRCHPWRSH4, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE5_LRCHPWRSH5, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE5_LRCHPWRSH6, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE5_LRCHPWRSH7, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE5_LRCHPWRSH8, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE5_LRCHPWRSH9, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE5_LRCHPWRSH10, 0)
        self._reg_write(model.vars.MODEM_LONGRANGE5_LRCHPWRSH11, 0)
