<?xml version='1.0' encoding='UTF-8'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="pin_tool.efr32.efr32mg2b.hadm" label="HADM" name="HADM" description="" version="A">
    <properties>
      <stringProperty label="Type" id="type" defaultValue="hadm" transient="true" hidden="true" readonly="true" description=""/>
      <stringProperty label="Custom Peripheral Name" id="peripheral.name" description=""/>
    </properties>
    <propertyCategories>
      <category label="HADM">
        <subCategory label="">
          <propertyRef refId="peripheral.name"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals>
      <signal name="HADM_ANT0"/>
      <signal name="HADM_ANT1"/>
      <signal name="HADM_ANT2"/>
      <signal name="HADM_ANT3"/>
    </signals>
  </module>
</module:DocumentRoot>
