from pycalcmodel.core.output import ModelOutputType, ModelOutput
from pyradioconfig.parts.common.profiles.lion_regs import build_modem_regs_lion


def build_modem_regs_curl(model,profile):
    build_modem_regs_lion(model, profile)

    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00_SET0CSDCOEFF0,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00.SET0CSDCOEFF0'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00_SET0CSDCOEFF1,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00.SET0CSDCOEFF1'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00_SET0CSDCOEFF2,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00.SET0CSDCOEFF2'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00_SET0CSDCOEFF3,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00.SET0CSDCOEFF3'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01_SET0CSDCOEFF4,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01.SET0CSDCOEFF4'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01_SET0CSDCOEFF5,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01.SET0CSDCOEFF5'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01_SET0CSDCOEFF6,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01.SET0CSDCOEFF6'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE02_SET0CSDCOEFF7,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE02.SET0CSDCOEFF7'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE02_SET0CSDCOEFF8,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE02.SET0CSDCOEFF8'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE02_SET0CSDCOEFF9,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE02.SET0CSDCOEFF9'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE03_SET0CSDCOEFF10, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE03.SET0CSDCOEFF10'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE03_SET0CSDCOEFF11, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE03.SET0CSDCOEFF11'))

    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00S_SET0CSDCOEFF0S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00S.SET0CSDCOEFF0S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00S_SET0CSDCOEFF1S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00S.SET0CSDCOEFF1S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00S_SET0CSDCOEFF2S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00S.SET0CSDCOEFF2S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00S_SET0CSDCOEFF3S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00S.SET0CSDCOEFF3S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00S_SET0CSDCOEFF4S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00S.SET0CSDCOEFF4S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00S_SET0CSDCOEFF5S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00S.SET0CSDCOEFF5S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00S_SET0CSDCOEFF6S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00S.SET0CSDCOEFF6S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01S_SET0CSDCOEFF7S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01S.SET0CSDCOEFF7S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01S_SET0CSDCOEFF8S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01S.SET0CSDCOEFF8S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01S_SET0CSDCOEFF9S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01S.SET0CSDCOEFF9S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01S_SET0CSDCOEFF10S, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01S.SET0CSDCOEFF10S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01S_SET0CSDCOEFF11S, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01S.SET0CSDCOEFF11S'))


    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10_SET1CSDCOEFF0,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10.SET1CSDCOEFF0'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10_SET1CSDCOEFF1,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10.SET1CSDCOEFF1'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10_SET1CSDCOEFF2,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10.SET1CSDCOEFF2'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10_SET1CSDCOEFF3,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10.SET1CSDCOEFF3'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE11_SET1CSDCOEFF4,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE11.SET1CSDCOEFF4'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE11_SET1CSDCOEFF5,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE11.SET1CSDCOEFF5'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE11_SET1CSDCOEFF6,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE11.SET1CSDCOEFF6'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE12_SET1CSDCOEFF7,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE12.SET1CSDCOEFF7'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE12_SET1CSDCOEFF8,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE12.SET1CSDCOEFF8'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE12_SET1CSDCOEFF9,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE12.SET1CSDCOEFF9'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE13_SET1CSDCOEFF10, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE13.SET1CSDCOEFF10'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE13_SET1CSDCOEFF11, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE13.SET1CSDCOEFF11'))

    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10S_SET1CSDCOEFF0S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10S.SET1CSDCOEFF0S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10S_SET1CSDCOEFF1S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10S.SET1CSDCOEFF1S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10S_SET1CSDCOEFF2S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10S.SET1CSDCOEFF2S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10S_SET1CSDCOEFF3S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10S.SET1CSDCOEFF3S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10S_SET1CSDCOEFF4S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10S.SET1CSDCOEFF4S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10S_SET1CSDCOEFF5S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10S.SET1CSDCOEFF5S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE10S_SET1CSDCOEFF6S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE10S.SET1CSDCOEFF6S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE11S_SET1CSDCOEFF7S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE11S.SET1CSDCOEFF7S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE11S_SET1CSDCOEFF8S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE11S.SET1CSDCOEFF8S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE11S_SET1CSDCOEFF9S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE11S.SET1CSDCOEFF9S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE11S_SET1CSDCOEFF10S, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE11S.SET1CSDCOEFF10S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE11S_SET1CSDCOEFF11S, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE11S.SET1CSDCOEFF11S'))

    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00NADM_NADMCSDCOEFF0,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00NADM.NADMCSDCOEFF0'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00NADM_NADMCSDCOEFF1,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00NADM.NADMCSDCOEFF1'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00NADM_NADMCSDCOEFF2,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00NADM.NADMCSDCOEFF2'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00NADM_NADMCSDCOEFF3,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00NADM.NADMCSDCOEFF3'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01NADM_NADMCSDCOEFF4,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01NADM.NADMCSDCOEFF4'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01NADM_NADMCSDCOEFF5,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01NADM.NADMCSDCOEFF5'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01NADM_NADMCSDCOEFF6,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01NADM.NADMCSDCOEFF6'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE02NADM_NADMCSDCOEFF7,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE02NADM.NADMCSDCOEFF7'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE02NADM_NADMCSDCOEFF8,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE02NADM.NADMCSDCOEFF8'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE02NADM_NADMCSDCOEFF9,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE02NADM.NADMCSDCOEFF9'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE03NADM_NADMCSDCOEFF10, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE03NADM.NADMCSDCOEFF10'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE03NADM_NADMCSDCOEFF11, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE03NADM.NADMCSDCOEFF11'))

    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00SNADM_NADMCSDCOEFF0S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF0S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00SNADM_NADMCSDCOEFF1S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF1S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00SNADM_NADMCSDCOEFF2S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF2S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00SNADM_NADMCSDCOEFF3S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF3S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00SNADM_NADMCSDCOEFF4S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF4S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00SNADM_NADMCSDCOEFF5S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF5S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE00SNADM_NADMCSDCOEFF6S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE00SNADM.NADMCSDCOEFF6S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01SNADM_NADMCSDCOEFF7S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF7S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01SNADM_NADMCSDCOEFF8S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF8S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01SNADM_NADMCSDCOEFF9S,  '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF9S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01SNADM_NADMCSDCOEFF10S, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF10S'))
    profile.outputs.append(ModelOutput(model.vars.MODEM_CHFCSDCOE01SNADM_NADMCSDCOEFF11S, '', ModelOutputType.SVD_REG_FIELD, readable_name='MODEM.CHFCSDCOE01SNADM.NADMCSDCOEFF11S'))
