from pyradioconfig.calculator_model_framework.interfaces.ipcalculator import IPRegFields


class ModRegFields(IPRegFields):
    reg_field_list = []

    def __init__(self):
        super().__init__()
        self.reg_field_list = [
            'CTRL0.MAPFSK',
            'CTRL0.CODING',
            'CTRL0.MODFORMAT',
            'CTRL0.OOKASYNCPIN',
            'CTRL0.DSSSLEN',
            'CTRL0.DSSSSHIFTS',
            'CTRL0.DSSSDOUBLE',
            'CTRL0.DIFFENCMODE',
            'CTRL0.SHAPING',
            'CTRL1.SYNCBITS',
            'CTRL1.TXSYNC',
            'CTRL1.SYNCDATA',
            'CTRL2.TXPINMODE',
            'CTRL2.BRDIVA',
            'CTRL2.BRDIVB',
            'CTRL2.DEVMULA',
            'CTRL2.DEVMULB',
            'CTRL2.RATESELMODE',
            'CTRL3.PRSDINEN',
            # 'CTRL3_DEVMULBCW',
            'CTRL4.PREDISTAVG',
            'CTRL6.TXDBPSKINV',
            'CTRL6.TXDBPSKRAMPEN',
            'CTRL6.CODINGB',
            'TXBR.TXBRNUM',
            'PRE.BASE',
            'PRE.BASEBITS',
            'PRE.PRESYMB4FSK',
            'PRE.DSSSPRE',
            'PRE.SYNCSYMB4FSK',
            'PRE.TXBASES',
            'DSSS0.DSSS0',
            'MODINDEX.MODINDEXM',
            'MODINDEX.MODINDEXE',
            # 'MODINDEX_AMMODINDEXM',
            # 'MODINDEX_AMMODINDEXE',
            'SHAPING0.COEFF0',
            'SHAPING0.COEFF1',
            'SHAPING0.COEFF2',
            'SHAPING0.COEFF3',
            'SHAPING1.COEFF4',
            'SHAPING1.COEFF5',
            'SHAPING1.COEFF6',
            'SHAPING1.COEFF7',
            'SHAPING2.COEFF8',
            'SHAPING2.COEFF9',
            'SHAPING2.COEFF10',
            'SHAPING2.COEFF11',
            'SHAPING3.COEFF12',
            'SHAPING3.COEFF13',
            'SHAPING3.COEFF14',
            'SHAPING3.COEFF15',
            'SHAPING4.COEFF16',
            'SHAPING4.COEFF17',
            'SHAPING4.COEFF18',
            'SHAPING4.COEFF19',
            'SHAPING5.COEFF20',
            'SHAPING5.COEFF21',
            'SHAPING5.COEFF22',
            'SHAPING5.COEFF23',
            'SHAPING6.COEFF24',
            'SHAPING6.COEFF25',
            'SHAPING6.COEFF26',
            'SHAPING6.COEFF27',
            'SHAPING7.COEFF28',
            'SHAPING7.COEFF29',
            'SHAPING7.COEFF30',
            'SHAPING7.COEFF31',
            'SHAPING8.COEFF32',
            'SHAPING8.COEFF33',
            'SHAPING8.COEFF34',
            'SHAPING8.COEFF35',
            'SHAPING9.COEFF36',
            'SHAPING9.COEFF37',
            'SHAPING9.COEFF38',
            'SHAPING9.COEFF39',
            'SHAPING10.COEFF40',
            'SHAPING10.COEFF41',
            'SHAPING10.COEFF42',
            'SHAPING10.COEFF43',
            'SHAPING11.COEFF44',
            'SHAPING11.COEFF45',
            'SHAPING11.COEFF46',
            'SHAPING11.COEFF47',
            'SHAPING12.COEFF48',
            'SHAPING12.COEFF49',
            'SHAPING12.COEFF50',
            'SHAPING12.COEFF51',
            'SHAPING13.COEFF52',
            'SHAPING13.COEFF53',
            'SHAPING13.COEFF54',
            'SHAPING13.COEFF55',
            'SHAPING14.COEFF56',
            'SHAPING14.COEFF57',
            'SHAPING14.COEFF58',
            'SHAPING14.COEFF59',
            'SHAPING15.COEFF60',
            'SHAPING15.COEFF61',
            'SHAPING15.COEFF62',
            'SHAPING15.COEFF63',
            # 'RAMPCTRL_RAMPRATE0',
            # 'RAMPCTRL_RAMPRATE1',
            # 'RAMPCTRL_RAMPRATE2',
            # 'RAMPCTRL_RAMPDIS',
            # 'RAMPCTRL_RAMPDISRST',
            # 'RAMPCTRL_RAMPVAL',
            # 'RAMPCTRL_RAMPMODE',
            # 'RAMPLEV_RAMPLEV0',
            # 'RAMPLEV_RAMPLEV1',
            # 'RAMPLEV_RAMPLEV2',
            # 'RAMPLEV_RAMPLEVOFFS',
            'ANTSWCTRL.ANTDFLTSEL',
            'ANTSWCTRL.ANTCOUNT',
            'ANTSWCTRL.ANTSWTYPE',
            # 'ANTSWCTRL_ANTSWRST',
            'ANTSWCTRL.CFGANTPATTEN',
            'ANTSWCTRL.ANTSWENABLE',
            'ANTSWCTRL.EXTDSTOPPULSECNT',
            'ANTSWCTRL1.TIMEPERIOD',
            'ANTSWSTART.ANTSWSTARTTIM',
            'ANTSWEND.ANTSWENDTIM',
            'CFGANTPATT.CFGANTPATTVAL',
            # 'SPARE_SPARE',
            'SYNC0.SYNC0',
            'SYNC1.SYNC1',
            'TXCTRL.TXMOD',
            'TXCTRL.BR2M',
            'TXCTRL.TXENDTIMER',
            # 'TXCTRL_FORCECLKEN',
            # 'TXCTRL_TXINTPEN',
            # 'TXCTRL_TXDSEN',
            'TXCTRL.TXAFIFOBYP',
            # 'TXCTRL_TXTIMTESTEN',
            'TXCTRL.IQMOD',
            # 'TXCTRL_TXDOFORCEI',
            # 'TXCTRL_TXDOFORCEQ',
            # 'TXDACVAL_TXFORCEDI',
            # 'TXDACVAL_TXFORCEDQ',
            # 'TXDACVAL_TXIDLEI',
            # 'TXDACVAL_TXIDLEQ',
            'TXCORRSTATIC.TXDGAIN',
            'TXCORRSTATIC.TXINVCORDICIN',
            'TXCORRSTATIC.TXIQSWAP',
            'TXCORRSTATIC.TXDACFORMAT',
            'TXCORRSTATIC.TXFREQCORR',
            # 'TXCORRPTE_TXIQIMBEN',
            # 'TXCORRPTE_TXGAINIMB',
            # 'TXCORRPTE_TXPHSIMB',
            # 'TXCORRPTE_TXDCI',
            # 'TXCORRPTE_TXDCQ',
            'CIC.CICRATIO',
            'CIC.CICGAIN',
            'SRCIQ.SRCRATIO',
            'TXCTRL.TXDACFREQ',
            'TXCTRL.TXDACSEL',
            'IQSHAPING1.IQSHAPINTERPRATIO',
            'IQSHAPING1.IQSHAPGAIN',
            'IQSHAPING1.IQSHAPCOEFF0',
            'IQSHAPING1.IQSHAPCOEFF1',
            'IQSHAPING2.IQSHAPCOEFF2',
            'IQSHAPING2.IQSHAPCOEFF3',
            'IQSHAPING2.IQSHAPCOEFF4',
            'IQSHAPING2.IQSHAPCOEFF5',
            'IQSHAPING3.IQSHAPCOEFF6',
            'IQSHAPING3.IQSHAPCOEFF7',
            'IQSHAPING3.IQSHAPCOEFF8',
            'IQSHAPING3.IQSHAPCOEFF9',
    ]