set(CMAKE_TRY_COMPILE_TARGET_TYPE       STATIC_LIBRARY)

set(CMAKE_C_STANDARD_REQUIRED   ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS          OFF)

set(SLED_DEFAULT_WARNINGS "-Wall -Wextra -Werror")

set(CMAKE_C_FLAGS_DEBUG                 "-Og -g ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE               "-Os -DNDEBUG ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO        "-Os -g -DNDEBUG ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG               "-Og -g ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE             "-Os -DNDEBUG ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO      "-Os -g -DNDEBUG ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM   NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY   ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE   ONLY)
