set(CMAKE_SYSTEM_NAME                   Generic)
set(CMAKE_SYSTEM_PROCESSOR              arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE       STATIC_LIBRARY)

if(WIN32)
    set(EXE_SUFFIX ".exe")
else()
    set(EXE_SUFFIX "")
endif()

set(TARGET_TRIPLET "arm-none-eabi-")
set(CMAKE_C_COMPILER    $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}gcc${EXE_SUFFIX})
set(CMAKE_CXX_COMPILER  $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}g++${EXE_SUFFIX})
set(CMAKE_ASM_COMPILER  $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}gcc${EXE_SUFFIX})
set(CMAKE_LINKER        $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}gcc${EXE_SUFFIX})
set(CMAKE_AR            $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}ar${EXE_SUFFIX})
set(CMAKE_SIZE_UTIL     $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}size${EXE_SUFFIX})
set(CMAKE_STRIP         $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}strip${EXE_SUFFIX})
set(CMAKE_OBJCOPY       $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}objcopy${EXE_SUFFIX})
set(CMAKE_OBJDUMP       $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}objdump${EXE_SUFFIX})
set(CMAKE_NM_UTIL       $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}gcc-nm${EXE_SUFFIX})
set(CMAKE_RANLIB        $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}gcc-ranlib${EXE_SUFFIX})
set(CMAKE_GCOV          $ENV{SLED_TOOL_GCC_ARM_PATH}${TARGET_TRIPLET}gcov${EXE_SUFFIX})

set(CMAKE_C_STANDARD_REQUIRED   ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS          OFF)

if(SLED_VARIANT_MODE STREQUAL "core")
    if(SLED_VARIANT STREQUAL "cortex-m0plus")
        set(CPU_FLAGS "-mcpu=cortex-m0plus -mthumb")
        set(FPU_FLAGS "")
    elseif(SLED_VARIANT STREQUAL "cortex-m3")
        set(CPU_FLAGS "-mcpu=cortex-m3 -mthumb")
        set(FPU_FLAGS "")
    elseif(SLED_VARIANT STREQUAL "cortex-m4")
        set(CPU_FLAGS "-mcpu=cortex-m4 -mthumb")
        set(FPU_FLAGS "-mfpu=fpv4-sp-d16 -mfloat-abi=softfp")
    elseif(SLED_VARIANT STREQUAL "cortex-m33")
        set(CPU_FLAGS "-mcpu=cortex-m33 -mthumb")
        set(FPU_FLAGS "-mfpu=fpv5-sp-d16 -mfloat-abi=hard")
    elseif(SLED_VARIANT STREQUAL "cortex-m55")
        set(CPU_FLAGS "-mcpu=cortex-m55 -mthumb")
        set(FPU_FLAGS "-mfpu=fpv5-sp-d16 -mfloat-abi=hard")
    endif()
elseif(SLED_VARIANT_MODE STREQUAL "architecture")
# TODO
endif()

set(CMAKE_C_FLAGS_INIT                  "${CPU_FLAGS} ${FPU_FLAGS} -ffunction-sections -fdata-sections -fomit-frame-pointer")
set(CMAKE_CXX_FLAGS_INIT                "${CMAKE_C_FLAGS_INIT} -fno-exceptions -fno-rtti")
set(CMAKE_ASM_FLAGS_INIT                "${CPU_FLAGS} ${FPU_FLAGS} -x assembler-with-cpp")
set(CMAKE_EXE_LINKER_FLAGS_INIT         "${CPU_FLAGS} ${FPU_FLAGS}")
set(CMAKE_STATIC_LINKER_FLAGS_INIT      "")

set(SLED_DEFAULT_WARNINGS "-Wall -Wextra -Werror")

set(CMAKE_C_FLAGS_DEBUG                 "-Og -g ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE               "-Os -DNDEBUG ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO        "-Os -g -DNDEBUG ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG               "-Og -g ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE             "-Os -DNDEBUG ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO      "-Os -g -DNDEBUG ${SLED_DEFAULT_WARNINGS}" CACHE STRING "")

#set(CMAKE_C_OUTPUT_EXTENSION            ".o")
#set(CMAKE_CXX_OUTPUT_EXTENSION          ".o")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM   NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY   ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE   ONLY)
