
# -*- coding: utf-8 -*-

__all__ = [ 'RM_Peripheral_HADM_S' ]

from . static import Base_RM_Peripheral
from . HADM_S_register import *

class RM_Peripheral_HADM_S(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_HADM_S, self).__init__(rmio, label,
            0xA8034000, 'HADM_S',
            u"",
            [])
        self.IPVERSION = RM_Register_HADM_S_IPVERSION(self.zz_rmio, self.zz_label)
        self.zz_rdict['IPVERSION'] = self.IPVERSION
        self.EN = RM_Register_HADM_S_EN(self.zz_rmio, self.zz_label)
        self.zz_rdict['EN'] = self.EN
        self.IEN = RM_Register_HADM_S_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.IF = RM_Register_HADM_S_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.SEQIEN = RM_Register_HADM_S_SEQIEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIEN'] = self.SEQIEN
        self.SEQIF = RM_Register_HADM_S_SEQIF(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIF'] = self.SEQIF
        self.FSWIEN = RM_Register_HADM_S_FSWIEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['FSWIEN'] = self.FSWIEN
        self.FSWIF = RM_Register_HADM_S_FSWIF(self.zz_rmio, self.zz_label)
        self.zz_rdict['FSWIF'] = self.FSWIF
        self.CMD = RM_Register_HADM_S_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.CTRL0 = RM_Register_HADM_S_CTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL0'] = self.CTRL0
        self.RTTCTRL0 = RM_Register_HADM_S_RTTCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTCTRL0'] = self.RTTCTRL0
        self.RTTCTRL1 = RM_Register_HADM_S_RTTCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTCTRL1'] = self.RTTCTRL1
        self.RTTCTRL2 = RM_Register_HADM_S_RTTCTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTCTRL2'] = self.RTTCTRL2
        self.RTTTUNE = RM_Register_HADM_S_RTTTUNE(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTTUNE'] = self.RTTTUNE
        self.RTTRPTTIME0 = RM_Register_HADM_S_RTTRPTTIME0(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTRPTTIME0'] = self.RTTRPTTIME0
        self.RTTRPTTIME1 = RM_Register_HADM_S_RTTRPTTIME1(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTRPTTIME1'] = self.RTTRPTTIME1
        self.RTTPKT0 = RM_Register_HADM_S_RTTPKT0(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTPKT0'] = self.RTTPKT0
        self.RTTPKT1 = RM_Register_HADM_S_RTTPKT1(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTPKT1'] = self.RTTPKT1
        self.RTTPKT2 = RM_Register_HADM_S_RTTPKT2(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTPKT2'] = self.RTTPKT2
        self.RTTPKT3 = RM_Register_HADM_S_RTTPKT3(self.zz_rmio, self.zz_label)
        self.zz_rdict['RTTPKT3'] = self.RTTPKT3
        self.PBRCTRL0 = RM_Register_HADM_S_PBRCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['PBRCTRL0'] = self.PBRCTRL0
        self.PBRCTRL1 = RM_Register_HADM_S_PBRCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['PBRCTRL1'] = self.PBRCTRL1
        self.PBRDCCOMP = RM_Register_HADM_S_PBRDCCOMP(self.zz_rmio, self.zz_label)
        self.zz_rdict['PBRDCCOMP'] = self.PBRDCCOMP
        self.PBRGDCOMP0 = RM_Register_HADM_S_PBRGDCOMP0(self.zz_rmio, self.zz_label)
        self.zz_rdict['PBRGDCOMP0'] = self.PBRGDCOMP0
        self.PBRGDCOMP1 = RM_Register_HADM_S_PBRGDCOMP1(self.zz_rmio, self.zz_label)
        self.zz_rdict['PBRGDCOMP1'] = self.PBRGDCOMP1
        self.PBRRAMPCTRL = RM_Register_HADM_S_PBRRAMPCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PBRRAMPCTRL'] = self.PBRRAMPCTRL
        self.ANTCTRL = RM_Register_HADM_S_ANTCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTCTRL'] = self.ANTCTRL
        self.PRSSEL = RM_Register_HADM_S_PRSSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRSSEL'] = self.PRSSEL
        self.RFECASEL = RM_Register_HADM_S_RFECASEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['RFECASEL'] = self.RFECASEL
        self.NADMCONFIG = RM_Register_HADM_S_NADMCONFIG(self.zz_rmio, self.zz_label)
        self.zz_rdict['NADMCONFIG'] = self.NADMCONFIG
        self.MSEPEARSONMASK = RM_Register_HADM_S_MSEPEARSONMASK(self.zz_rmio, self.zz_label)
        self.zz_rdict['MSEPEARSONMASK'] = self.MSEPEARSONMASK
        self.DFTAMFREQ = RM_Register_HADM_S_DFTAMFREQ(self.zz_rmio, self.zz_label)
        self.zz_rdict['DFTAMFREQ'] = self.DFTAMFREQ
        self.DFTECLDFREQ = RM_Register_HADM_S_DFTECLDFREQ(self.zz_rmio, self.zz_label)
        self.zz_rdict['DFTECLDFREQ'] = self.DFTECLDFREQ
        self.REFGENCOEFFG0 = RM_Register_HADM_S_REFGENCOEFFG0(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG0'] = self.REFGENCOEFFG0
        self.REFGENCOEFFG1 = RM_Register_HADM_S_REFGENCOEFFG1(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG1'] = self.REFGENCOEFFG1
        self.REFGENCOEFFG2 = RM_Register_HADM_S_REFGENCOEFFG2(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG2'] = self.REFGENCOEFFG2
        self.REFGENCOEFFG3 = RM_Register_HADM_S_REFGENCOEFFG3(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG3'] = self.REFGENCOEFFG3
        self.REFGENCOEFFG4 = RM_Register_HADM_S_REFGENCOEFFG4(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG4'] = self.REFGENCOEFFG4
        self.REFGENCOEFFG5 = RM_Register_HADM_S_REFGENCOEFFG5(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG5'] = self.REFGENCOEFFG5
        self.REFGENCOEFFG6 = RM_Register_HADM_S_REFGENCOEFFG6(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG6'] = self.REFGENCOEFFG6
        self.REFGENCOEFFG7 = RM_Register_HADM_S_REFGENCOEFFG7(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG7'] = self.REFGENCOEFFG7
        self.REFGENCOEFFG8 = RM_Register_HADM_S_REFGENCOEFFG8(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG8'] = self.REFGENCOEFFG8
        self.REFGENCOEFFG9 = RM_Register_HADM_S_REFGENCOEFFG9(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG9'] = self.REFGENCOEFFG9
        self.REFGENCOEFFG10 = RM_Register_HADM_S_REFGENCOEFFG10(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG10'] = self.REFGENCOEFFG10
        self.REFGENCOEFFG11 = RM_Register_HADM_S_REFGENCOEFFG11(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG11'] = self.REFGENCOEFFG11
        self.REFGENCOEFFG12 = RM_Register_HADM_S_REFGENCOEFFG12(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG12'] = self.REFGENCOEFFG12
        self.REFGENCOEFFG13 = RM_Register_HADM_S_REFGENCOEFFG13(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG13'] = self.REFGENCOEFFG13
        self.REFGENCOEFFG14 = RM_Register_HADM_S_REFGENCOEFFG14(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG14'] = self.REFGENCOEFFG14
        self.REFGENCOEFFG15 = RM_Register_HADM_S_REFGENCOEFFG15(self.zz_rmio, self.zz_label)
        self.zz_rdict['REFGENCOEFFG15'] = self.REFGENCOEFFG15
        self.SPARE = RM_Register_HADM_S_SPARE(self.zz_rmio, self.zz_label)
        self.zz_rdict['SPARE'] = self.SPARE
        self.RESCTRL = RM_Register_HADM_S_RESCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['RESCTRL'] = self.RESCTRL
        self.ADDR = RM_Register_HADM_S_ADDR(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADDR'] = self.ADDR
        self.RESSTATUS = RM_Register_HADM_S_RESSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['RESSTATUS'] = self.RESSTATUS
        self.THRESHOLDCTRL = RM_Register_HADM_S_THRESHOLDCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['THRESHOLDCTRL'] = self.THRESHOLDCTRL
        self.AHBCONFIG = RM_Register_HADM_S_AHBCONFIG(self.zz_rmio, self.zz_label)
        self.zz_rdict['AHBCONFIG'] = self.AHBCONFIG
        self.TASKCTRL0 = RM_Register_HADM_S_TASKCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TASKCTRL0'] = self.TASKCTRL0
        self.TASKCTRL1 = RM_Register_HADM_S_TASKCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['TASKCTRL1'] = self.TASKCTRL1
        self.TASKCTRL2 = RM_Register_HADM_S_TASKCTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['TASKCTRL2'] = self.TASKCTRL2
        self.TASKCTRL3 = RM_Register_HADM_S_TASKCTRL3(self.zz_rmio, self.zz_label)
        self.zz_rdict['TASKCTRL3'] = self.TASKCTRL3
        self.RESULTINSTR0 = RM_Register_HADM_S_RESULTINSTR0(self.zz_rmio, self.zz_label)
        self.zz_rdict['RESULTINSTR0'] = self.RESULTINSTR0
        self.INSTR00 = RM_Register_HADM_S_INSTR00(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR00'] = self.INSTR00
        self.INSTR10 = RM_Register_HADM_S_INSTR10(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR10'] = self.INSTR10
        self.INSTR20 = RM_Register_HADM_S_INSTR20(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR20'] = self.INSTR20
        self.INSTR30 = RM_Register_HADM_S_INSTR30(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR30'] = self.INSTR30
        self.INSTR40 = RM_Register_HADM_S_INSTR40(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR40'] = self.INSTR40
        self.INSTR50 = RM_Register_HADM_S_INSTR50(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR50'] = self.INSTR50
        self.INSTR60 = RM_Register_HADM_S_INSTR60(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR60'] = self.INSTR60
        self.RESULTINSTR1 = RM_Register_HADM_S_RESULTINSTR1(self.zz_rmio, self.zz_label)
        self.zz_rdict['RESULTINSTR1'] = self.RESULTINSTR1
        self.INSTR01 = RM_Register_HADM_S_INSTR01(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR01'] = self.INSTR01
        self.INSTR11 = RM_Register_HADM_S_INSTR11(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR11'] = self.INSTR11
        self.INSTR21 = RM_Register_HADM_S_INSTR21(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR21'] = self.INSTR21
        self.INSTR31 = RM_Register_HADM_S_INSTR31(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR31'] = self.INSTR31
        self.INSTR41 = RM_Register_HADM_S_INSTR41(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR41'] = self.INSTR41
        self.INSTR51 = RM_Register_HADM_S_INSTR51(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR51'] = self.INSTR51
        self.INSTR61 = RM_Register_HADM_S_INSTR61(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR61'] = self.INSTR61
        self.RESULTINSTR2 = RM_Register_HADM_S_RESULTINSTR2(self.zz_rmio, self.zz_label)
        self.zz_rdict['RESULTINSTR2'] = self.RESULTINSTR2
        self.INSTR02 = RM_Register_HADM_S_INSTR02(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR02'] = self.INSTR02
        self.INSTR12 = RM_Register_HADM_S_INSTR12(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR12'] = self.INSTR12
        self.INSTR22 = RM_Register_HADM_S_INSTR22(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR22'] = self.INSTR22
        self.INSTR32 = RM_Register_HADM_S_INSTR32(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR32'] = self.INSTR32
        self.INSTR42 = RM_Register_HADM_S_INSTR42(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR42'] = self.INSTR42
        self.INSTR52 = RM_Register_HADM_S_INSTR52(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR52'] = self.INSTR52
        self.INSTR62 = RM_Register_HADM_S_INSTR62(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR62'] = self.INSTR62
        self.RESULTINSTR3 = RM_Register_HADM_S_RESULTINSTR3(self.zz_rmio, self.zz_label)
        self.zz_rdict['RESULTINSTR3'] = self.RESULTINSTR3
        self.INSTR03 = RM_Register_HADM_S_INSTR03(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR03'] = self.INSTR03
        self.INSTR13 = RM_Register_HADM_S_INSTR13(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR13'] = self.INSTR13
        self.INSTR23 = RM_Register_HADM_S_INSTR23(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR23'] = self.INSTR23
        self.INSTR33 = RM_Register_HADM_S_INSTR33(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR33'] = self.INSTR33
        self.INSTR43 = RM_Register_HADM_S_INSTR43(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR43'] = self.INSTR43
        self.INSTR53 = RM_Register_HADM_S_INSTR53(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR53'] = self.INSTR53
        self.INSTR63 = RM_Register_HADM_S_INSTR63(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSTR63'] = self.INSTR63
        self.STATUS0 = RM_Register_HADM_S_STATUS0(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS0'] = self.STATUS0
        self.STATUS1 = RM_Register_HADM_S_STATUS1(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS1'] = self.STATUS1
        self.STATUS2 = RM_Register_HADM_S_STATUS2(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS2'] = self.STATUS2
        self.STATUS3 = RM_Register_HADM_S_STATUS3(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS3'] = self.STATUS3
        self.STATUS4 = RM_Register_HADM_S_STATUS4(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS4'] = self.STATUS4
        self.STATUS5 = RM_Register_HADM_S_STATUS5(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS5'] = self.STATUS5
        self.STATUS6 = RM_Register_HADM_S_STATUS6(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS6'] = self.STATUS6
        self.STATUS7 = RM_Register_HADM_S_STATUS7(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS7'] = self.STATUS7
        self.__dict__['zz_frozen'] = True