toolchains:
  - gcc
  - iar
  - llvm

hwfilter:
   device_includes:
    - device_supports_rail
   device_excludes:
    - device_no_rail_api
    - device_family_bgm22
    - device_family_bgm27
   board_excludes:
    - brd1019a
    - brd1021a
    - brd2503a
    - brd2503b
    - brd2504a
    - brd2505a
    - brd2506a
    - brd2606a
