from pyradioconfig.calculator_model_framework.interfaces.ipcalculator import IPRegFields


class ModemRegFields(IPRegFields):
    reg_field_list = []

    def __init__(self):
        super().__init__()
        self.reg_field_list = [
            'ADCTRL1.ADCTRL1',
            'ADCTRL2.ADCTRL2',
            'ADFSM0.ADSTAT1SEL',
            'ADFSM0.ADSTAT2SEL',
            'ADFSM0.ADSTATREAD',
            'ADPC1.ADPCCORROFFSETCHIP',
            'ADPC1.ADPCEN',
            'ADPC1.ADPCTIMINGBAUDS',
            'ADPC1.ADPCWNDCNT',
            'ADPC1.ADPCWNDSIZECHIP',
            'ADPC10.ADBBSSAMPJUMP',
            'ADPC10.ADBBSSCHANGEEN',
            'ADPC10.ADBBSSCHGDNTHR',
            'ADPC10.ADBBSSCHGUPTHR',
            'ADPC2.ADENCORR32',
            'ADPC2.ADPCCORRSAMPLES',
            'ADPC2.ADPCPRETIMINGBAUDS',
            'ADPC2.ADPCSIGAMPTHR',
            'ADPC2.ADPCWNDCNTRST',
            'ADPC3.ADBBSSAMPEXP',
            'ADPC3.ADBBSSAMPMANT',
            'ADPC3.ADBBSSAVGEN',
            'ADPC3.ADBBSSAVGFREEZE',
            'ADPC3.ADBBSSAVGPER',
            'ADPC3.ADBBSSAVGWAIT',
            'ADPC3.ADBBSSEN',
            'ADPC3.ADBBSSFILTLENGTH',
            'ADPC3.ADBBSSSELWRDATA',
            'ADPC4.ADBBSSAMPLUT0',
            'ADPC4.ADBBSSAMPLUT1',
            'ADPC4.ADBBSSAMPLUT2',
            'ADPC4.ADBBSSAMPLUT3',
            'ADPC5.ADBBSSAMPLUT4',
            'ADPC5.ADBBSSAMPLUT5',
            'ADPC5.ADBBSSAMPLUT6',
            'ADPC5.ADBBSSAMPLUT7',
            'ADPC6.ADBBSSAMPLUT10',
            'ADPC6.ADBBSSAMPLUT11',
            'ADPC6.ADBBSSAMPLUT8',
            'ADPC6.ADBBSSAMPLUT9',
            'ADPC7.ADBBSSAMPLUT12',
            'ADPC7.ADBBSSAMPLUT13',
            'ADPC7.ADBBSSAMPLUT14',
            'ADPC7.ADBBSSAMPLUT15',
            'ADPC8.ADPCANTSAMPBUF',
            'ADPC8.ADPCANTSAMPOFFSET',
            'ADPC8.ADPCANTSAMPSWITCH',
            'ADPC8.ADPCANTSAMPSWITCHWAIT',
            'ADPC8.ADPCANTSAMPWRITE',
            'ADPC8.ADPCOSR',
            'ADPC9.ADBBSSAMPAVGLIM',
            'ADPC9.ADBBSSAMPTHR',
            'ADPC9.ADBBSSDNTHR',
            'ADPC9.ADBBSSSYNCEN',
            'ADPC9.ADBBSSUPTHR',
            'ADQUAL4.ADAGCGRTHR',
            'ADQUAL4.ADGRMODE',
            'ADQUAL4.ADRSSIGRTHR',
            'ADQUAL5.ADDIRECTCORR',
            'ADQUAL6.ADBACORRDIFF',
            'ADQUAL6.ADBACORRTHR',
            'ADQUAL7.ADBARSSIDIFF',
            'ADQUAL7.ADBARSSITHR',
            'ADQUAL8.ADBAAGCTHR',
            'ADQUAL8.ADBACORRTHR2',
            'ADQUAL8.ADBAMODE',
            'AFC.AFCAVGPER',
            'AFC.AFCDEL',
            'AFC.AFCDELDET',
            'AFC.AFCDSAFREQOFFEST',
            'AFC.AFCENINTCOMP',
            'AFC.AFCGEAR',
            'AFC.AFCLIMRESET',
            'AFC.AFCONESHOT',
            'AFC.AFCRXCLR',
            'AFC.AFCRXMODE',
            'AFC.AFCTXMODE',
            'AFC.DISAFCCTE',
            'AFCADJLIM.AFCADJLIM',
            'AFCADJRX.AFCSCALEE',
            'AFCADJRX.AFCSCALEM',
            'AFCADJTX.AFCSCALEE',
            'AFCADJTX.AFCSCALEM',
            'ANTDIVCTRL.ADPRETHRESH',
            'ANTDIVCTRL.ENADPRETHRESH',
            'ANTSWCTRL.ANTSWENABLE',
            'ANTSWCTRL.CFGANTPATTEN',
            'ANTSWCTRL1.TIMEPERIOD',
            'AUTOCG.AUTOCGEN',
            'CF.DEC2',
            'CGCLKSTOP.FORCEOFF',
            'CHFCTRL.ADJGAINWIN',
            'CHFSWCTRL.CHFSWTIME',
            'COCURRMODE.CONCURRENT',
            'COCURRMODE.CORRCHKMUTE',
            'COCURRMODE.DSSSCONCURRENT',
            'COCURRMODE.DSSSDSACHK',
            'COCURRMODE.TRECSDSACHK',
            'COH0.COHCHPWRLOCK',
            'COH0.COHCHPWRRESTART',
            'COH0.COHCHPWRTH0',
            'COH0.COHCHPWRTH1',
            'COH0.COHCHPWRTH2',
            'COH0.COHDYNAMICBBSSEN',
            'COH0.COHDYNAMICPRETHRESH',
            'COH0.COHDYNAMICPRETHRESHSEL',
            'COH0.COHDYNAMICSYNCTHRESH',
            'COH1.SYNCTHRESH0',
            'COH1.SYNCTHRESH1',
            'COH1.SYNCTHRESH2',
            'COH1.SYNCTHRESH3',
            'COH2.DSAPEAKCHPWRTH',
            'COH2.FIXEDCDTHFORIIR',
            'COH2.SYNCTHRESHDELTA0',
            'COH2.SYNCTHRESHDELTA1',
            'COH2.SYNCTHRESHDELTA2',
            'COH2.SYNCTHRESHDELTA3',
            'COH3.CDSS',
            'COH3.COHDSAADDWNDSIZE',
            'COH3.COHDSACMPLX',
            'COH3.COHDSADETDIS',
            'COH3.COHDSAEN',
            'COH3.DSAPEAKCHKEN',
            'COH3.DSAPEAKCHPWREN',
            'COH3.DSAPEAKINDLEN',
            'COH3.DYNIIRCOEFOPTION',
            'COH3.LOGICBASEDCOHDEMODGATE',
            'COH3.ONEPEAKQUALEN',
            'COH3.PEAKCHKTIMOUT',
            'CTRL0.CODING',
            'CTRL0.DEMODRAWDATASEL',
            'CTRL0.DETDIS',
            'CTRL0.DIFFENCMODE',
            'CTRL0.DSSSDOUBLE',
            'CTRL0.DSSSLEN',
            'CTRL0.DSSSSHIFTS',
            'CTRL0.DUALCORROPTDIS',
            'CTRL0.FDM0DIFFDIS',
            'CTRL0.FRAMEDETDEL',
            'CTRL0.MAPFSK',
            'CTRL0.MODFORMAT',
            # 'CTRL0.OOKASYNCPIN',
            # 'CTRL0.SHAPING',
            'CTRL1.COMPMODE',
            'CTRL1.FREQOFFESTLIM',
            'CTRL1.FREQOFFESTPER',
            'CTRL1.PHASEDEMOD',
            'CTRL1.RESYNCPER',
            'CTRL1.SYNC1INV',
            'CTRL1.SYNCBITS',
            # 'CTRL1.SYNCDATA',
            'CTRL1.SYNCERRORS',
            # 'CTRL1.TXSYNC',
            'CTRL2.BRDIVA',
            'CTRL2.BRDIVB',
            'CTRL2.DATAFILTER',
            # 'CTRL2.DEVMULA',
            # 'CTRL2.DEVMULB',
            'CTRL2.DEVWEIGHTDIS',
            'CTRL2.DMASEL',
            'CTRL2.RATESELMODE',
            'CTRL2.RXFRCDIS',
            'CTRL2.SQITHRESH',
            # 'CTRL2.TXPINMODE',
            'CTRL3.ANTDIVMODE',
            # 'CTRL3.PRSDINEN',
            'CTRL3.RAMTESTEN',
            'CTRL3.TIMINGBASESGAIN',
            'CTRL3.TSAMPDEL',
            'CTRL3.TSAMPLIM',
            'CTRL3.TSAMPMODE',
            'CTRL4.ADCSATDENS',
            'CTRL4.ADCSATLEVEL',
            'CTRL4.CLKUNDIVREQ',
            'CTRL4.DEVOFFCOMP',
            'CTRL4.ISICOMP',
            'CTRL4.OFFSETPHASEMASKING',
            'CTRL4.OFFSETPHASESCALING',
            'CTRL4.PHASECLICKFILT',
            'CTRL4.SOFTDSSSMODE',
            'CTRL5.BBSS',
            'CTRL5.BRCALAVG',
            'CTRL5.BRCALEN',
            'CTRL5.BRCALMODE',
            'CTRL5.DEMODRAWDATASEL2',
            'CTRL5.DETDEL',
            'CTRL5.DSSSCTD',
            'CTRL5.FOEPREAVG',
            'CTRL5.LINCORR',
            'CTRL5.POEPER',
            'CTRL5.RESYNCBAUDTRANS',
            'CTRL5.RESYNCLIMIT',
            'CTRL5.TDEDGE',
            'CTRL5.TREDGE',
            'CTRL6.ARW',
            # 'CTRL6.CODINGB',
            'CTRL6.CPLXCORREN',
            'CTRL6.DEMODRESTARTALL',
            'CTRL6.DSSS3SYMBOLSYNCEN',
            'CTRL6.PREBASES',
            'CTRL6.PSTIMABORT0',
            'CTRL6.PSTIMABORT1',
            'CTRL6.PSTIMABORT2',
            'CTRL6.PSTIMABORT3',
            'CTRL6.RXBRCALCDIS',
            'CTRL6.RXRESTARTUPONRSSI',
            'CTRL6.RXRESTARTUPONSHORTRSSI',
            'CTRL6.TDREW',
            'CTRL6.TIMTHRESHGAIN',
            # 'CTRL6.TXDBPSKINV',
            # 'CTRL6.TXDBPSKRAMPEN',
            'DIGMIXCTRL.BLEORZB',
            'DIGMIXCTRL.DSSSCFECOMBO',
            'DIGMIXCTRL.FWHOPPING',
            'DIGMIXCTRL.HOPPINGSRC',
            'DIGMIXCTRL.MULTIPHYHOP',
            'DIGMIXCTRL.RXBRINTSHIFT',
            'DSSS0.DSSS0',
            'DUALTIM.DUALTIMEN',
            'DUALTIM.MINCOSTTHD2',
            'DUALTIM.SYNCACQWIN2',
            'EHDSSSCFG0.DSSSPATT',
            'EHDSSSCFG1.DSSSCORRTHD',
            'EHDSSSCFG1.DSSSDSAQTHD',
            'EHDSSSCFG1.DSSSEXPSYNCLEN',
            'EHDSSSCFG2.DSSSCORRSCHWIN',
            'EHDSSSCFG2.DSSSDSAQUALEN',
            'EHDSSSCFG2.DSSSFRTCORRTHD',
            'EHDSSSCFG2.DSSSTIMCORRTHD',
            'EHDSSSCFG2.DSSSTRACKINGWIN',
            'EHDSSSCFG2.MAXSCHMODE',
            'EHDSSSCFG2.ONESYMBOLMBDD',
            'EHDSSSCFG3.DSSSDASMAXTHD',
            'EHDSSSCFG3.DSSSFOETRACKGEAR',
            'EHDSSSCFG3.DSSSINITIMLEN',
            'EHDSSSCFG3.LQIAVGWIN',
            'EHDSSSCFG3.OPMODE',
            'EHDSSSCTRL.DSSSDSATHD',
            'EHDSSSCTRL.DSSSFRMTIMEOUT',
            'EHDSSSCTRL.DSSSFRQLIM',
            'EHDSSSCTRL.DSSSPMTIMEOUT',
            'EHDSSSCTRL.DSSSTIMEACQUTHD',
            'EHDSSSCTRL.DUALDSA',
            'EHDSSSCTRL.EHDSSSEN',
            'EHDSSSCTRL.FOEBIAS',
            'EHDSSSCTRL.FREQCORREN',
            'ETSTIM.ETSCOUNTEREN',
            'ETSTIM.ETSTIMVAL',
            'EXPECTPATTDUAL.EXPECTPATTDUAL',
            'FRMSCHTIME.DSARSTSYCNEN',
            'FRMSCHTIME.FRMSCHTIME',
            'FRMSCHTIME.PMENDSCHEN',
            'FRMSCHTIME.PMRSTSYCNEN',
            'INTAFC.FOEPREAVG0',
            'INTAFC.FOEPREAVG1',
            'INTAFC.FOEPREAVG2',
            'INTAFC.FOEPREAVG3',
            'INTAFC.FOEPREAVG4',
            'INTAFC.FOEPREAVG5',
            'INTAFC.FOEPREAVG6',
            'INTAFC.FOEPREAVG7',
            'LONGRANGE.LRBLE',
            'LONGRANGE.LRBLEDSA',
            'LONGRANGE.LRCORRSCHWIN',
            'LONGRANGE.LRCORRTHD',
            'LONGRANGE.LRDEC',
            'LONGRANGE.LRTIMCORRTHD',
            'LONGRANGE1.AVGWIN',
            'LONGRANGE1.CHPWRACCUDEL',
            'LONGRANGE1.HYSVAL',
            'LONGRANGE1.LOGICBASEDLRDEMODGATE',
            'LONGRANGE1.LOGICBASEDPUGATE',
            'LONGRANGE1.LRSPIKETHADD',
            'LONGRANGE1.LRSS',
            'LONGRANGE1.LRTIMEOUTTHD',
            'LONGRANGE1.PREFILTLEN',
            'LONGRANGE2.LRCHPWRTH1',
            'LONGRANGE2.LRCHPWRTH2',
            'LONGRANGE2.LRCHPWRTH3',
            'LONGRANGE2.LRCHPWRTH4',
            'LONGRANGE3.LRCHPWRTH5',
            'LONGRANGE3.LRCHPWRTH6',
            'LONGRANGE3.LRCHPWRTH7',
            'LONGRANGE3.LRCHPWRTH8',
            'LONGRANGE4.LRCHPWRSH1',
            'LONGRANGE4.LRCHPWRSH2',
            'LONGRANGE4.LRCHPWRSH3',
            'LONGRANGE4.LRCHPWRSH4',
            'LONGRANGE4.LRCHPWRTH10',
            'LONGRANGE4.LRCHPWRTH9',
            'LONGRANGE5.LRCHPWRSH10',
            'LONGRANGE5.LRCHPWRSH11',
            'LONGRANGE5.LRCHPWRSH5',
            'LONGRANGE5.LRCHPWRSH6',
            'LONGRANGE5.LRCHPWRSH7',
            'LONGRANGE5.LRCHPWRSH8',
            'LONGRANGE5.LRCHPWRSH9',
            'LONGRANGE6.LRCHPWRSH12',
            'LONGRANGE6.LRCHPWRSPIKETH',
            'LONGRANGE6.LRCHPWRTH11',
            'LONGRANGE6.LRSPIKETHD',
            'LRFRC.CI500',
            'LRFRC.FRCACKTIMETHD',
            'LRFRC.LRCORRMODE',
            'LRFRC.LRDSACORRTHD',
            'MODINDEX.FREQGAINE',
            'MODINDEX.FREQGAINM',
            # 'MODINDEX.MODINDEXE',
            # 'MODINDEX.MODINDEXM',
            'PHANTDECSION.CORRANDDIVTHD',
            'PHANTDECSION.RSSIANDDIVTHD',
            'PHANTDECSION.RSSICORR0',
            'PHANTDECSION.RSSICORR1',
            'PHANTDECSION.RSSICORR2',
            'PHANTDECSION.RSSICORR3',
            'PHDMODANTDIV.ANTWAIT',
            'PHDMODANTDIV.SKIP2ANT',
            'PHDMODANTDIV.SKIPCORRTHD',
            'PHDMODANTDIV.SKIPRSSITHD',
            'PHDMODCTRL.BCRDETECTOR',
            'PHDMODCTRL.BCRLEGACYCONC',
            'PHDMODCTRL.BCRTRECSCONC',
            'PHDMODCTRL.CHPWRQUAL',
            'PHDMODCTRL.FASTHOPPINGEN',
            'PHDMODCTRL.PMDETEN',
            'PHDMODCTRL.PMDETTHD',
            'PHDMODCTRL.PMTIMLOSEN',
            'PHDMODCTRL.PMTIMLOSTHD',
            'PHDMODCTRL.REMODDWN',
            'PHDMODCTRL.REMODEN',
            'PHDMODCTRL.REMODOSR',
            'PHDMODCTRL.REMODOUTSEL',
            'PHDMODCTRL.RSSIFLTBYP',
            'PRE.BASE',
            'PRE.BASEBITS',
            # 'PRE.DSSSPRE',
            'PRE.PREERRORS',
            # 'PRE.PRESYMB4FSK',
            'PRE.PREWNDERRORS',
            'PRE.SYNCSYMB4FSK',
            # 'PRE.TXBASES',
            'PREFILTCOEFF.PREFILTCOEFF',
            'REALTIMCFE.MINCOSTTHD',
            'REALTIMCFE.RTCFEEN',
            'REALTIMCFE.RTSCHMODE',
            'REALTIMCFE.RTSCHWIN',
            'REALTIMCFE.SINEWEN',
            'REALTIMCFE.SYNCACQWIN',
            'REALTIMCFE.TRACKINGWIN',
            'REALTIMCFE.VTAFCFRAME',
            'RXBR.RXBRDEN',
            'RXBR.RXBRINT',
            'RXBR.RXBRNUM',
            'RXRESTART.ANTSWRSTFLTTDIS',
            'RXRESTART.FLTRSTEN',
            'RXRESTART.RXRESTARTB4PREDET',
            'RXRESTART.RXRESTARTMACOMPENSEL',
            'RXRESTART.RXRESTARTMALATCHSEL',
            'RXRESTART.RXRESTARTMATAP',
            'RXRESTART.RXRESTARTMATHRESHOLD',
            'RXRESTART.RXRESTARTUPONMARSSI',
            # 'SHAPING0.COEFF0',
            # 'SHAPING0.COEFF1',
            # 'SHAPING0.COEFF2',
            # 'SHAPING0.COEFF3',
            # 'SHAPING1.COEFF4',
            # 'SHAPING1.COEFF5',
            # 'SHAPING1.COEFF6',
            # 'SHAPING1.COEFF7',
            # 'SHAPING10.COEFF40',
            # 'SHAPING10.COEFF41',
            # 'SHAPING10.COEFF42',
            # 'SHAPING10.COEFF43',
            # 'SHAPING11.COEFF44',
            # 'SHAPING11.COEFF45',
            # 'SHAPING11.COEFF46',
            # 'SHAPING11.COEFF47',
            # 'SHAPING12.COEFF48',
            # 'SHAPING12.COEFF49',
            # 'SHAPING12.COEFF50',
            # 'SHAPING12.COEFF51',
            # 'SHAPING13.COEFF52',
            # 'SHAPING13.COEFF53',
            # 'SHAPING13.COEFF54',
            # 'SHAPING13.COEFF55',
            # 'SHAPING14.COEFF56',
            # 'SHAPING14.COEFF57',
            # 'SHAPING14.COEFF58',
            # 'SHAPING14.COEFF59',
            # 'SHAPING15.COEFF60',
            # 'SHAPING15.COEFF61',
            # 'SHAPING15.COEFF62',
            # 'SHAPING15.COEFF63',
            # 'SHAPING2.COEFF10',
            # 'SHAPING2.COEFF11',
            # 'SHAPING2.COEFF8',
            # 'SHAPING2.COEFF9',
            # 'SHAPING3.COEFF12',
            # 'SHAPING3.COEFF13',
            # 'SHAPING3.COEFF14',
            # 'SHAPING3.COEFF15',
            # 'SHAPING4.COEFF16',
            # 'SHAPING4.COEFF17',
            # 'SHAPING4.COEFF18',
            # 'SHAPING4.COEFF19',
            # 'SHAPING5.COEFF20',
            # 'SHAPING5.COEFF21',
            # 'SHAPING5.COEFF22',
            # 'SHAPING5.COEFF23',
            # 'SHAPING6.COEFF24',
            # 'SHAPING6.COEFF25',
            # 'SHAPING6.COEFF26',
            # 'SHAPING6.COEFF27',
            # 'SHAPING7.COEFF28',
            # 'SHAPING7.COEFF29',
            # 'SHAPING7.COEFF30',
            # 'SHAPING7.COEFF31',
            # 'SHAPING8.COEFF32',
            # 'SHAPING8.COEFF33',
            # 'SHAPING8.COEFF34',
            # 'SHAPING8.COEFF35',
            # 'SHAPING9.COEFF36',
            # 'SHAPING9.COEFF37',
            # 'SHAPING9.COEFF38',
            # 'SHAPING9.COEFF39',
            'SICORR.CORRTHRESH',
            'SICORR.CORRTHRESH2SYMB',
            'SICORR.CORRTHRESHLOW',
            'SICORR.CORRTHRESHUP',
            'SICTRL0.FREQNOMINAL',
            'SICTRL0.NOISETHRESH',
            'SICTRL0.NOISETHRESHADJ',
            'SICTRL0.PEAKNUMADJ',
            'SICTRL0.PEAKNUMTHRESHLW',
            'SICTRL0.SIMODE',
            'SICTRL0.SYMIDENTDIS',
            'SICTRL1.FASTMODE',
            'SICTRL1.FREQOFFTOLERANCE',
            'SICTRL1.PEAKNUMP2ADJ',
            'SICTRL1.SMALLSAMPLETHRESH',
            'SICTRL1.SOFTCLIPBYPASS',
            'SICTRL1.SOFTCLIPTHRESH',
            'SICTRL1.SUPERCHIPTOLERANCE',
            'SICTRL1.TWOSYMBEN',
            'SICTRL1.ZCEN',
            'SICTRL1.ZCSAMPLETHRESH',
            'SICTRL2.AGCRSTUPONSI',
            'SICTRL2.CORRNUM',
            'SICTRL2.DISSIFRAMEDET',
            'SICTRL2.NARROWPULSETHRESH',
            'SICTRL2.PEAKNUMADJEN',
            'SICTRL2.SHFTWIN',
            'SICTRL2.SIRSTAGCMODE',
            'SICTRL2.SIRSTCCAMODE',
            'SICTRL2.SIRSTPRSMODE',
            'SICTRL2.SISTARTDELAY',
            'SICTRL2.SISTARTDELAYMODE',
            'SICTRL2.SUPERCHIPNUM',
            # TODO: Add to lpwh72000 when available in register map
            # 'SIFASTDETECTCTRL.FASTCWDETECTEN',
            # 'SIFASTDETECTCTRL.FASTSUPERCHIPEN',
            # 'SIFASTDETECTCTRL.FASTNARROWPULSEEN',
            # 'SIFASTDETECTCTRL.EYEOPENINGMODE',
            # 'SIFASTDETECTCTRL.CWDETECTSTARTWINDOW',
            # 'SIFASTDETECTCTRL.CWDETECTTHRESHOLD',
            # 'SIFASTDETECTCTRL.SUPERCHIPSTARTWINDOW',
            # 'SIFASTDETECTCTRL.NPULSEFIXEDTHRESHOLD',
            # 'SIFASTDETECTCTRL.NPULSETHRESHADJEN',
            # 'SIFASTDETECTCTRL.NPULSETHRESHADJ',
            'SQ.SQEN',
            'SQ.SQTIMOUT',
            'SQEXT.SQSTG2TIMOUT',
            'SQEXT.SQSTG3TIMOUT',
            'SRCCHF.CHMUTETIMER',
            'SYNC0.SYNC0',
            'SYNC1.SYNC1',
            'SYNC2.SYNC2',
            'SYNC3.SYNC3',
            'SYNCPROPERTIES.STATICSYNCTHRESH',
            'SYNCPROPERTIES.STATICSYNCTHRESHEN',
            'SYNCWORDCTRL.DUALSYNC',
            'SYNCWORDCTRL.DUALSYNC2TH',
            'SYNCWORDCTRL.SYNC0ERRORS',
            'SYNCWORDCTRL.SYNC1ERRORS',
            'SYNCWORDCTRL.SYNC2ERRORS',
            'SYNCWORDCTRL.SYNC3ERRORS',
            'SYNCWORDCTRL.SYNCBITS2TH',
            'SYNCWORDCTRL.SYNCDET2TH',
            'SYNCWORDCTRL.SYNCSWFEC',
            'TIMING.ADDTIMSEQ',
            'TIMING.FASTRESYNC',
            'TIMING.FDM0THRESH',
            'TIMING.OFFSUBDEN',
            'TIMING.OFFSUBNUM',
            'TIMING.TIMINGBASES',
            'TIMING.TIMSEQINVEN',
            'TIMING.TIMSEQSYNC',
            'TIMING.TIMTHRESH',
            'TIMING.TSAGCDEL',
            'TRECPMDET.COSTHYST',
            'TRECPMDET.PHSCALE',
            'TRECPMDET.PMACQUINGWIN',
            'TRECPMDET.PMCOSTVALTHD',
            'TRECPMDET.PMMINCOSTTHD',
            'TRECPMDET.PMTIMEOUTSEL',
            'TRECPMDET.PREAMSCH',
            'TRECPMPATT.PMEXPECTPATT',
            'TRECSCFG.PMOFFSET',
            'TRECSCFG.SDSCALE',
            'TRECSCFG.SOFTD',
            'TRECSCFG.TRECSOSR',
            # DTIMLOSS feature for fast switch PHY optimization. See https://jira.silabs.com/browse/MCUW_RADIO_CFG-2525
            'TRECSCFG.DTIMLOSSEN',
            'TRECSCFG.DTIMLOSSTHD',
            # 'TXBR.TXBRNUM',
            # 'TXCTRL.BR2M',
            # 'TXCTRL.IQMOD',
            # 'TXCTRL.TXAFIFOBYP',
            # 'TXCTRL.TXMOD',
            'VITERBIDEMOD.CORRCYCLE',
            'VITERBIDEMOD.CORRSTPSIZE',
            'VITERBIDEMOD.HARDDECISION',
            'VITERBIDEMOD.SYNTHAFC',
            'VITERBIDEMOD.VITERBIKSI1',
            'VITERBIDEMOD.VITERBIKSI2',
            'VITERBIDEMOD.VITERBIKSI3',
            'VITERBIDEMOD.VTDEMODEN',
            'VTBLETIMING.DISDEMODOF',
            'VTBLETIMING.FLENOFF',
            'VTBLETIMING.TIMINGDELAY',
            'VTBLETIMING.VTBLETIMINGSEL',
            'VTCORRCFG0.EXPECTPATT',
            'VTCORRCFG1.EXPECTHT',
            'VTCORRCFG1.EXPSYNCLEN',
            'VTCORRCFG1.KSI3SWENABLE',
            'VTCORRCFG1.VITERBIKSI3WB',
            'VTCORRCFG1.VTFRQLIM',
            'VTTRACK.FREQBIAS',
            'VTTRACK.FREQTRACKMODE',
            'VTTRACK.HIPWRTHD',
            'VTTRACK.TIMEACQUTHD',
            'VTTRACK.TIMGEAR',
            'VTTRACK.TIMTRACKTHD'
        ]